type: "post-processing"
input_dir: "data/task_outputs/factscore_decomposition/"
output_dir: "data/task_outputs/factscore_core_processing/"
post_processors:
  - type: "decontextualization"
    model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    base_url: "http://localhost:9871/v1"
    api_key: "token-abc123"
  - type: "claim-checkworthiness"
    bleached_templates: 
      - "{meta::topic} is a person."
      - "{meta::topic} breathes."
      - "{meta::topic} exists."
      - "{meta::topic} is a name."
      - "{meta::topic} is unique."
      - "{meta::topic} is famous."
      - "{meta::topic} has some abilities."
      - "somebody knows {meta::topic}."
      - "{meta::topic} is a star."
    entailer:
      type: "soft-entailer"
      model_name: "Zhengping/roberta-large-unli"
      max_length: 256
      internal_batch_size: 32
      cache_dir: ".cache/"
    cap_entailer:
      type: "default"
      model_name: "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
      max_length: 256
      internal_batch_size: 32
      cache_dir: ".cache/"
  - type: "sent-checkworthiness"
    model_name: "mistralai/Mistral-7B-Instruct-v0.2"
    base_url: "http://localhost:9871/v1"
    api_key: "token-abc123"
  - type: "core"
    entailer:
      type: "default"
      model_name: "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
      max_length: 256
      internal_batch_size: 32
      cache_dir: ".cache/"
    claim_checkworthiness_path: "meta::__claim-checkworthiness::score"
    sent_checkworthiness_path: "meta::__sent-checkworthiness::score"
dependencies:
  decomposition: "configs/factscore_decomposition.yaml"