type: "post-processing"
input_dir: "data/task_outputs/veriscore_other_processing/"
output_dir: "data/task_outputs/veriscore_core_processing/"
post_processors:
  - type: "core"
    entailer:
      type: "default"
      model_name: "MoritzLaurer/DeBERTa-v3-base-mnli-fever-anli"
      max_length: 256
      internal_batch_size: 32
      cache_dir: ".cache/"
    claim_checkworthiness_path: "meta::__claim-checkworthiness::score"
    sent_checkworthiness_path: "meta::__sent-checkworthiness::score"
dependencies:
  decomposition: "configs/veriscore_other_post_processing.yaml"